### ISSUE TITLE
Could not get upper_bound

### ISSUE THREAD

**Issue by mifne** [carrascomj/rust_sbml#16]
Hello,Thank you for maintaining this project. 
I am using version 0.7.0 of rust_sbml and when I try to get the upper_bound of the reaction structure, it returns None.

The lower_bound is outputting correctly, so I checked base_types.rs and it is #[serde(rename = “fbc:lowerUpperBound”)].
I think it is probably #[serde(rename = “fbc:upperFluxBound”)], could you please fix it?
I am just starting to learn Ruby and am new to submitting issues, so please let me know if there is any information I am missing.

Reaction: ID = R_r_1546, Lower bound = FB3N0, Upper bound = None
```
#[serde(rename = "fbc:lowerFluxBound")]
pub lower_bound: Option<String>,
#[serde(rename = "fbc:lowerUpperBound")]
pub upper_bound: Option<String>,
```

**Comment by carrascomj** [comment]
Good catch, thanks! I will get around this end of the week, probably I should add more tests.

**Comment by mifne** [comment]
Thank you for your response. 
I look forward to seeing that accomplished!

**Comment by carrascomj** [comment]
It should be fixed now, let me know if you run into any other issues! I will make a release, although it has been a while since the last one, I hope the CI is still functional.
